Changed URL of GDC QueryGL
* Replace "https://gdc-api.nci.nih.gov" with "https://api.gdc.cancer.gov"
* Also added more error checking.  Will die if system calls fail

diff --git a/queryGDC b/queryGDC
--- a/queryGDC
+++ b/queryGDC
@@ -5,6 +5,7 @@
 #
 # -t token.txt: define token file; may also be defined by `export GDC_TOKEN=file`.  Default ./gdc-user-token.txt
 # -v: print diagnostic information to stderr
+# -S: Verbose curl output (turns off `curl -s` flag)
 # -r: repeat query in case of timeout errors until succeeds.  Stops on other errors.
 # -d: dry run.  Print query but do not execute
 # 
@@ -17,18 +18,46 @@
 # m.wyczalkowski@wustl.edu
 # Ding Lab, Washington University School of Medicine
 
+# #########
+
+# Called after running scripts to catch fatal (exit 1) errors
+# works with piped calls ( S1 | S2 | S3 > OUT )
+# Usage:
+#   bash script.sh DATA | python script.py > $OUT
+#   test_exit_status # Calls `exit V` if any script in a pipe returns an exit value V which is not 0
+function test_exit_status {
+    # Evaluate return value for chain of pipes; see https://stackoverflow.com/questions/90418/exit-shell-script-based-on-process-exit-code
+    # exit code 137 is fatal error signal 9: http://tldp.org/LDP/abs/html/exitcodes.html
+    rcs=${PIPESTATUS[*]};
+    for rc in ${rcs}; do
+        if [[ $rc != 0 ]]; then
+            >&2 echo Fatal error.  Exiting
+            exit $rc;
+        fi;
+    done
+}
+
+
 # usage: run_query QUERY_JSON t
 # where t is token string
 function run_query {
     QUERY_JSON=$1
     t=$2
-    
+
+    # -s is silent.  It keeps download progress bar from appearing, but also discards warnings.
+    if [ -z $CURL_NO_SILENT ]; then
+        ARGS="-s $ARGS"
+    fi
+
+    URL="https://api.gdc.cancer.gov/v0/submission/graphql"
+
     if [ $DRYRUN ]; then
-        >&2 echo curl -s -XPOST -H \"X-Auth-Token: $t\" https://gdc-api.nci.nih.gov/v0/submission/graphql --data \"$QUERY_JSON\" 
+        >&2 echo curl $ARGS -XPOST -H \"X-Auth-Token: $t\" $URL --data \"$QUERY_JSON\" 
         >&2 echo Exiting after dry run.
-        exit
+        exit 0
     else
-        curl -s -XPOST -H "X-Auth-Token: $t" https://gdc-api.nci.nih.gov/v0/submission/graphql --data "$QUERY_JSON" 
+        curl $ARGS -XPOST -H "X-Auth-Token: $t" $URL --data "$QUERY_JSON" 
+        test_exit_status 
     fi
 }
 
@@ -42,8 +71,8 @@ function run_query_retry {
     t=$2
 
     R=$(run_query "$QUERY_JSON" "$t")  
-
     ERR=$(echo $R | jq -r '.errors[]? ')
+    test_exit_status
 
     if [ -z "$ERR" ]; then
         if [ $VERBOSE ]; then
@@ -84,6 +113,7 @@ function get_json {
     else
         python -c "$PY" < $GQL
     fi
+    test_exit_status
 }
 
 # If GDC_TOKEN not defined by environment variable, set it to default value
@@ -91,7 +121,7 @@ if [ -z $GDC_TOKEN ]; then
 GDC_TOKEN="gdc-user-token.txt"
 fi
 
-while getopts ":t:vrd" opt; do
+while getopts ":t:vrdS" opt; do
   case $opt in
     v)  
       VERBOSE=1
@@ -104,6 +134,9 @@ while getopts ":t:vrd" opt; do
       ;;
     t)
       GDC_TOKEN=$OPTARG
+      ;;
+    S)  
+      CURL_NO_SILENT=1
       ;;
     \?)
       >&2 echo "Invalid option: -$OPTARG" >&2
@@ -121,7 +154,7 @@ shift $((OPTIND-1))
 if [ "$#" -ne 1 ]; then
     >&2 echo queryGDC error: Wrong number of arguments
     >&2 echo Usage: queryGDC \[options\] query.dat
-    exit
+    exit 1
 fi
 
 if [ $VERBOSE ]; then
@@ -130,7 +163,7 @@ fi
 
 if [ ! -f $GDC_TOKEN ]; then
     >&2 echo Token $GDC_TOKEN not found
-    exit
+    exit 1
 fi
 T=$(cat $GDC_TOKEN)
 
